name: audio_wave
description: A highly customizable bar graph(or wave graph) with animation, color, radius, spaces, etc.
version: 0.1.0
homepage: https://github.com/thruthesky/audio_wave

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
